//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AMS
{
    public partial class ActivityLog
    {
        public int ActivityID { get; set; }
        public int MembershipID { get; set; }
        public string TableName { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Action { get; set; }
        public string IPAddress { get; set; }
    }
    
}
