//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AMSModel", "FK__Appointme__DayPr__3D5E1FD2", "DayPreferences", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AMS.DayPreference), "AppointmentAvail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AMS.AppointmentAvail), true)]
[assembly: EdmRelationshipAttribute("AMSModel", "FK__Appointme__CustI__3E52440B", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AMS.Customer), "Appointments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AMS.Appointment), true)]
[assembly: EdmRelationshipAttribute("AMSModel", "FK__Appointme__UserI__3F466844", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AMS.User), "Appointments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AMS.Appointment), true)]
[assembly: EdmRelationshipAttribute("AMSModel", "FK__Users__CompanyID__4316F928", "Company", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AMS.Company), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AMS.User), true)]
[assembly: EdmRelationshipAttribute("AMSModel", "FK__DayPrefer__UserP__403A8C7D", "UserPreferences", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AMS.UserPreference), "DayPreferences", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AMS.DayPreference), true)]
[assembly: EdmRelationshipAttribute("AMSModel", "FK__TimePrefe__DayPr__412EB0B6", "DayPreferences", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AMS.DayPreference), "TimePreferences", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AMS.TimePreference), true)]
[assembly: EdmRelationshipAttribute("AMSModel", "FK__UserPrefe__UserI__4222D4EF", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AMS.User), "UserPreferences", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AMS.UserPreference), true)]

#endregion

namespace AMS
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AMSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AMSEntities object using the connection string found in the 'AMSEntities' section of the application configuration file.
        /// </summary>
        public AMSEntities() : base("name=AMSEntities", "AMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AMSEntities object.
        /// </summary>
        public AMSEntities(string connectionString) : base(connectionString, "AMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AMSEntities object.
        /// </summary>
        public AMSEntities(EntityConnection connection) : base(connection, "AMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ActivityLog> ActivityLogs
        {
            get
            {
                if ((_ActivityLogs == null))
                {
                    _ActivityLogs = base.CreateObjectSet<ActivityLog>("ActivityLogs");
                }
                return _ActivityLogs;
            }
        }
        private ObjectSet<ActivityLog> _ActivityLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AppointmentAvail> AppointmentAvails
        {
            get
            {
                if ((_AppointmentAvails == null))
                {
                    _AppointmentAvails = base.CreateObjectSet<AppointmentAvail>("AppointmentAvails");
                }
                return _AppointmentAvails;
            }
        }
        private ObjectSet<AppointmentAvail> _AppointmentAvails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Appointment> Appointments
        {
            get
            {
                if ((_Appointments == null))
                {
                    _Appointments = base.CreateObjectSet<Appointment>("Appointments");
                }
                return _Appointments;
            }
        }
        private ObjectSet<Appointment> _Appointments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Company> Companies
        {
            get
            {
                if ((_Companies == null))
                {
                    _Companies = base.CreateObjectSet<Company>("Companies");
                }
                return _Companies;
            }
        }
        private ObjectSet<Company> _Companies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DayPreference> DayPreferences
        {
            get
            {
                if ((_DayPreferences == null))
                {
                    _DayPreferences = base.CreateObjectSet<DayPreference>("DayPreferences");
                }
                return _DayPreferences;
            }
        }
        private ObjectSet<DayPreference> _DayPreferences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ErrorLog> ErrorLogs
        {
            get
            {
                if ((_ErrorLogs == null))
                {
                    _ErrorLogs = base.CreateObjectSet<ErrorLog>("ErrorLogs");
                }
                return _ErrorLogs;
            }
        }
        private ObjectSet<ErrorLog> _ErrorLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TimePreference> TimePreferences
        {
            get
            {
                if ((_TimePreferences == null))
                {
                    _TimePreferences = base.CreateObjectSet<TimePreference>("TimePreferences");
                }
                return _TimePreferences;
            }
        }
        private ObjectSet<TimePreference> _TimePreferences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserPreference> UserPreferences
        {
            get
            {
                if ((_UserPreferences == null))
                {
                    _UserPreferences = base.CreateObjectSet<UserPreference>("UserPreferences");
                }
                return _UserPreferences;
            }
        }
        private ObjectSet<UserPreference> _UserPreferences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ActivityLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActivityLogs(ActivityLog activityLog)
        {
            base.AddObject("ActivityLogs", activityLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AppointmentAvails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppointmentAvails(AppointmentAvail appointmentAvail)
        {
            base.AddObject("AppointmentAvails", appointmentAvail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Appointments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppointments(Appointment appointment)
        {
            base.AddObject("Appointments", appointment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Companies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DayPreferences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDayPreferences(DayPreference dayPreference)
        {
            base.AddObject("DayPreferences", dayPreference);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ErrorLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToErrorLogs(ErrorLog errorLog)
        {
            base.AddObject("ErrorLogs", errorLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TimePreferences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTimePreferences(TimePreference timePreference)
        {
            base.AddObject("TimePreferences", timePreference);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserPreferences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserPreferences(UserPreference userPreference)
        {
            base.AddObject("UserPreferences", userPreference);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="ActivityLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActivityLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ActivityLog object.
        /// </summary>
        /// <param name="activityID">Initial value of the ActivityID property.</param>
        /// <param name="membershipID">Initial value of the MembershipID property.</param>
        /// <param name="tableName">Initial value of the TableName property.</param>
        /// <param name="dateTime">Initial value of the DateTime property.</param>
        /// <param name="action">Initial value of the Action property.</param>
        /// <param name="iPAddress">Initial value of the IPAddress property.</param>
        public static ActivityLog CreateActivityLog(global::System.Int32 activityID, global::System.Int32 membershipID, global::System.String tableName, global::System.DateTime dateTime, global::System.String action, global::System.String iPAddress)
        {
            ActivityLog activityLog = new ActivityLog();
            activityLog.ActivityID = activityID;
            activityLog.MembershipID = membershipID;
            activityLog.TableName = tableName;
            activityLog.DateTime = dateTime;
            activityLog.Action = action;
            activityLog.IPAddress = iPAddress;
            return activityLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.Int32 _ActivityID;
        partial void OnActivityIDChanging(global::System.Int32 value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MembershipID
        {
            get
            {
                return _MembershipID;
            }
            set
            {
                OnMembershipIDChanging(value);
                ReportPropertyChanging("MembershipID");
                _MembershipID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MembershipID");
                OnMembershipIDChanged();
            }
        }
        private global::System.Int32 _MembershipID;
        partial void OnMembershipIDChanging(global::System.Int32 value);
        partial void OnMembershipIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TableName
        {
            get
            {
                return _TableName;
            }
            set
            {
                OnTableNameChanging(value);
                ReportPropertyChanging("TableName");
                _TableName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TableName");
                OnTableNameChanged();
            }
        }
        private global::System.String _TableName;
        partial void OnTableNameChanging(global::System.String value);
        partial void OnTableNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IPAddress
        {
            get
            {
                return _IPAddress;
            }
            set
            {
                OnIPAddressChanging(value);
                ReportPropertyChanging("IPAddress");
                _IPAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IPAddress");
                OnIPAddressChanged();
            }
        }
        private global::System.String _IPAddress;
        partial void OnIPAddressChanging(global::System.String value);
        partial void OnIPAddressChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Appointment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Appointment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Appointment object.
        /// </summary>
        /// <param name="appointmentID">Initial value of the AppointmentID property.</param>
        /// <param name="appointmentNo">Initial value of the AppointmentNo property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="timeFrom">Initial value of the TimeFrom property.</param>
        /// <param name="timeTo">Initial value of the TimeTo property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="custID">Initial value of the CustID property.</param>
        public static Appointment CreateAppointment(global::System.Int32 appointmentID, global::System.Int32 appointmentNo, global::System.DateTime date, global::System.TimeSpan timeFrom, global::System.TimeSpan timeTo, global::System.Int32 userID, global::System.Int32 custID)
        {
            Appointment appointment = new Appointment();
            appointment.AppointmentID = appointmentID;
            appointment.AppointmentNo = appointmentNo;
            appointment.Date = date;
            appointment.TimeFrom = timeFrom;
            appointment.TimeTo = timeTo;
            appointment.UserID = userID;
            appointment.CustID = custID;
            return appointment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppointmentID
        {
            get
            {
                return _AppointmentID;
            }
            set
            {
                if (_AppointmentID != value)
                {
                    OnAppointmentIDChanging(value);
                    ReportPropertyChanging("AppointmentID");
                    _AppointmentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppointmentID");
                    OnAppointmentIDChanged();
                }
            }
        }
        private global::System.Int32 _AppointmentID;
        partial void OnAppointmentIDChanging(global::System.Int32 value);
        partial void OnAppointmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppointmentNo
        {
            get
            {
                return _AppointmentNo;
            }
            set
            {
                OnAppointmentNoChanging(value);
                ReportPropertyChanging("AppointmentNo");
                _AppointmentNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppointmentNo");
                OnAppointmentNoChanged();
            }
        }
        private global::System.Int32 _AppointmentNo;
        partial void OnAppointmentNoChanging(global::System.Int32 value);
        partial void OnAppointmentNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan TimeFrom
        {
            get
            {
                return _TimeFrom;
            }
            set
            {
                OnTimeFromChanging(value);
                ReportPropertyChanging("TimeFrom");
                _TimeFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeFrom");
                OnTimeFromChanged();
            }
        }
        private global::System.TimeSpan _TimeFrom;
        partial void OnTimeFromChanging(global::System.TimeSpan value);
        partial void OnTimeFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan TimeTo
        {
            get
            {
                return _TimeTo;
            }
            set
            {
                OnTimeToChanging(value);
                ReportPropertyChanging("TimeTo");
                _TimeTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeTo");
                OnTimeToChanged();
            }
        }
        private global::System.TimeSpan _TimeTo;
        partial void OnTimeToChanging(global::System.TimeSpan value);
        partial void OnTimeToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustID
        {
            get
            {
                return _CustID;
            }
            set
            {
                OnCustIDChanging(value);
                ReportPropertyChanging("CustID");
                _CustID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustID");
                OnCustIDChanged();
            }
        }
        private global::System.Int32 _CustID;
        partial void OnCustIDChanging(global::System.Int32 value);
        partial void OnCustIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _Status;
        partial void OnStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__Appointme__CustI__3E52440B", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("AMSModel.FK__Appointme__CustI__3E52440B", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("AMSModel.FK__Appointme__CustI__3E52440B", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("AMSModel.FK__Appointme__CustI__3E52440B", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("AMSModel.FK__Appointme__CustI__3E52440B", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__Appointme__UserI__3F466844", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AMSModel.FK__Appointme__UserI__3F466844", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AMSModel.FK__Appointme__UserI__3F466844", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AMSModel.FK__Appointme__UserI__3F466844", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("AMSModel.FK__Appointme__UserI__3F466844", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="AppointmentAvail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AppointmentAvail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AppointmentAvail object.
        /// </summary>
        /// <param name="appAvailID">Initial value of the AppAvailID property.</param>
        /// <param name="dayPrefID">Initial value of the DayPrefID property.</param>
        /// <param name="appDate">Initial value of the AppDate property.</param>
        public static AppointmentAvail CreateAppointmentAvail(global::System.Int32 appAvailID, global::System.Int32 dayPrefID, global::System.DateTime appDate)
        {
            AppointmentAvail appointmentAvail = new AppointmentAvail();
            appointmentAvail.AppAvailID = appAvailID;
            appointmentAvail.DayPrefID = dayPrefID;
            appointmentAvail.AppDate = appDate;
            return appointmentAvail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppAvailID
        {
            get
            {
                return _AppAvailID;
            }
            set
            {
                if (_AppAvailID != value)
                {
                    OnAppAvailIDChanging(value);
                    ReportPropertyChanging("AppAvailID");
                    _AppAvailID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppAvailID");
                    OnAppAvailIDChanged();
                }
            }
        }
        private global::System.Int32 _AppAvailID;
        partial void OnAppAvailIDChanging(global::System.Int32 value);
        partial void OnAppAvailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DayPrefID
        {
            get
            {
                return _DayPrefID;
            }
            set
            {
                OnDayPrefIDChanging(value);
                ReportPropertyChanging("DayPrefID");
                _DayPrefID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPrefID");
                OnDayPrefIDChanged();
            }
        }
        private global::System.Int32 _DayPrefID;
        partial void OnDayPrefIDChanging(global::System.Int32 value);
        partial void OnDayPrefIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AppDate
        {
            get
            {
                return _AppDate;
            }
            set
            {
                OnAppDateChanging(value);
                ReportPropertyChanging("AppDate");
                _AppDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppDate");
                OnAppDateChanged();
            }
        }
        private global::System.DateTime _AppDate;
        partial void OnAppDateChanging(global::System.DateTime value);
        partial void OnAppDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _Status;
        partial void OnStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__Appointme__DayPr__3D5E1FD2", "DayPreferences")]
        public DayPreference DayPreference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DayPreference>("AMSModel.FK__Appointme__DayPr__3D5E1FD2", "DayPreferences").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DayPreference>("AMSModel.FK__Appointme__DayPr__3D5E1FD2", "DayPreferences").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DayPreference> DayPreferenceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DayPreference>("AMSModel.FK__Appointme__DayPr__3D5E1FD2", "DayPreferences");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DayPreference>("AMSModel.FK__Appointme__DayPr__3D5E1FD2", "DayPreferences", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Company")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Company : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="companyID">Initial value of the CompanyID property.</param>
        /// <param name="companyName">Initial value of the CompanyName property.</param>
        public static Company CreateCompany(global::System.Int32 companyID, global::System.String companyName)
        {
            Company company = new Company();
            company.CompanyID = companyID;
            company.CompanyName = companyName;
            return company;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CompanyID
        {
            get
            {
                return _CompanyID;
            }
            set
            {
                if (_CompanyID != value)
                {
                    OnCompanyIDChanging(value);
                    ReportPropertyChanging("CompanyID");
                    _CompanyID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CompanyID");
                    OnCompanyIDChanged();
                }
            }
        }
        private global::System.Int32 _CompanyID;
        partial void OnCompanyIDChanging(global::System.Int32 value);
        partial void OnCompanyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyAddress
        {
            get
            {
                return _CompanyAddress;
            }
            set
            {
                OnCompanyAddressChanging(value);
                ReportPropertyChanging("CompanyAddress");
                _CompanyAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyAddress");
                OnCompanyAddressChanged();
            }
        }
        private global::System.String _CompanyAddress;
        partial void OnCompanyAddressChanging(global::System.String value);
        partial void OnCompanyAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyPhone
        {
            get
            {
                return _CompanyPhone;
            }
            set
            {
                OnCompanyPhoneChanging(value);
                ReportPropertyChanging("CompanyPhone");
                _CompanyPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyPhone");
                OnCompanyPhoneChanged();
            }
        }
        private global::System.String _CompanyPhone;
        partial void OnCompanyPhoneChanging(global::System.String value);
        partial void OnCompanyPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] CompanyLogo
        {
            get
            {
                return StructuralObject.GetValidValue(_CompanyLogo);
            }
            set
            {
                OnCompanyLogoChanging(value);
                ReportPropertyChanging("CompanyLogo");
                _CompanyLogo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyLogo");
                OnCompanyLogoChanged();
            }
        }
        private global::System.Byte[] _CompanyLogo;
        partial void OnCompanyLogoChanging(global::System.Byte[] value);
        partial void OnCompanyLogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CompanyStatus
        {
            get
            {
                return _CompanyStatus;
            }
            set
            {
                OnCompanyStatusChanging(value);
                ReportPropertyChanging("CompanyStatus");
                _CompanyStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyStatus");
                OnCompanyStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _CompanyStatus;
        partial void OnCompanyStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnCompanyStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__Users__CompanyID__4316F928", "Users")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("AMSModel.FK__Users__CompanyID__4316F928", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("AMSModel.FK__Users__CompanyID__4316F928", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        /// <param name="membershipUserID">Initial value of the MembershipUserID property.</param>
        /// <param name="custFirstName">Initial value of the CustFirstName property.</param>
        /// <param name="custLastName">Initial value of the CustLastName property.</param>
        public static Customer CreateCustomer(global::System.Int32 customerID, global::System.Int32 membershipUserID, global::System.String custFirstName, global::System.String custLastName)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.MembershipUserID = membershipUserID;
            customer.CustFirstName = custFirstName;
            customer.CustLastName = custLastName;
            return customer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MembershipUserID
        {
            get
            {
                return _MembershipUserID;
            }
            set
            {
                OnMembershipUserIDChanging(value);
                ReportPropertyChanging("MembershipUserID");
                _MembershipUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MembershipUserID");
                OnMembershipUserIDChanged();
            }
        }
        private global::System.Int32 _MembershipUserID;
        partial void OnMembershipUserIDChanging(global::System.Int32 value);
        partial void OnMembershipUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustFirstName
        {
            get
            {
                return _CustFirstName;
            }
            set
            {
                OnCustFirstNameChanging(value);
                ReportPropertyChanging("CustFirstName");
                _CustFirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustFirstName");
                OnCustFirstNameChanged();
            }
        }
        private global::System.String _CustFirstName;
        partial void OnCustFirstNameChanging(global::System.String value);
        partial void OnCustFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustLastName
        {
            get
            {
                return _CustLastName;
            }
            set
            {
                OnCustLastNameChanging(value);
                ReportPropertyChanging("CustLastName");
                _CustLastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustLastName");
                OnCustLastNameChanged();
            }
        }
        private global::System.String _CustLastName;
        partial void OnCustLastNameChanging(global::System.String value);
        partial void OnCustLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustEmail
        {
            get
            {
                return _CustEmail;
            }
            set
            {
                OnCustEmailChanging(value);
                ReportPropertyChanging("CustEmail");
                _CustEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustEmail");
                OnCustEmailChanged();
            }
        }
        private global::System.String _CustEmail;
        partial void OnCustEmailChanging(global::System.String value);
        partial void OnCustEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustDescription
        {
            get
            {
                return _CustDescription;
            }
            set
            {
                OnCustDescriptionChanging(value);
                ReportPropertyChanging("CustDescription");
                _CustDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustDescription");
                OnCustDescriptionChanged();
            }
        }
        private global::System.String _CustDescription;
        partial void OnCustDescriptionChanging(global::System.String value);
        partial void OnCustDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustPhone
        {
            get
            {
                return _CustPhone;
            }
            set
            {
                OnCustPhoneChanging(value);
                ReportPropertyChanging("CustPhone");
                _CustPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustPhone");
                OnCustPhoneChanged();
            }
        }
        private global::System.String _CustPhone;
        partial void OnCustPhoneChanging(global::System.String value);
        partial void OnCustPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CustStatus
        {
            get
            {
                return _CustStatus;
            }
            set
            {
                OnCustStatusChanging(value);
                ReportPropertyChanging("CustStatus");
                _CustStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustStatus");
                OnCustStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _CustStatus;
        partial void OnCustStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnCustStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__Appointme__CustI__3E52440B", "Appointments")]
        public EntityCollection<Appointment> Appointments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Appointment>("AMSModel.FK__Appointme__CustI__3E52440B", "Appointments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Appointment>("AMSModel.FK__Appointme__CustI__3E52440B", "Appointments", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="DayPreference")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DayPreference : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DayPreference object.
        /// </summary>
        /// <param name="dayPrefID">Initial value of the DayPrefID property.</param>
        /// <param name="userPrefID">Initial value of the UserPrefID property.</param>
        /// <param name="day">Initial value of the Day property.</param>
        public static DayPreference CreateDayPreference(global::System.Int32 dayPrefID, global::System.Int32 userPrefID, global::System.String day)
        {
            DayPreference dayPreference = new DayPreference();
            dayPreference.DayPrefID = dayPrefID;
            dayPreference.UserPrefID = userPrefID;
            dayPreference.Day = day;
            return dayPreference;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DayPrefID
        {
            get
            {
                return _DayPrefID;
            }
            set
            {
                if (_DayPrefID != value)
                {
                    OnDayPrefIDChanging(value);
                    ReportPropertyChanging("DayPrefID");
                    _DayPrefID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DayPrefID");
                    OnDayPrefIDChanged();
                }
            }
        }
        private global::System.Int32 _DayPrefID;
        partial void OnDayPrefIDChanging(global::System.Int32 value);
        partial void OnDayPrefIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserPrefID
        {
            get
            {
                return _UserPrefID;
            }
            set
            {
                OnUserPrefIDChanging(value);
                ReportPropertyChanging("UserPrefID");
                _UserPrefID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserPrefID");
                OnUserPrefIDChanged();
            }
        }
        private global::System.Int32 _UserPrefID;
        partial void OnUserPrefIDChanging(global::System.Int32 value);
        partial void OnUserPrefIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Day
        {
            get
            {
                return _Day;
            }
            set
            {
                OnDayChanging(value);
                ReportPropertyChanging("Day");
                _Day = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Day");
                OnDayChanged();
            }
        }
        private global::System.String _Day;
        partial void OnDayChanging(global::System.String value);
        partial void OnDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _Status;
        partial void OnStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__Appointme__DayPr__3D5E1FD2", "AppointmentAvail")]
        public EntityCollection<AppointmentAvail> AppointmentAvails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AppointmentAvail>("AMSModel.FK__Appointme__DayPr__3D5E1FD2", "AppointmentAvail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AppointmentAvail>("AMSModel.FK__Appointme__DayPr__3D5E1FD2", "AppointmentAvail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__DayPrefer__UserP__403A8C7D", "UserPreferences")]
        public UserPreference UserPreference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserPreference>("AMSModel.FK__DayPrefer__UserP__403A8C7D", "UserPreferences").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserPreference>("AMSModel.FK__DayPrefer__UserP__403A8C7D", "UserPreferences").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserPreference> UserPreferenceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserPreference>("AMSModel.FK__DayPrefer__UserP__403A8C7D", "UserPreferences");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserPreference>("AMSModel.FK__DayPrefer__UserP__403A8C7D", "UserPreferences", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__TimePrefe__DayPr__412EB0B6", "TimePreferences")]
        public EntityCollection<TimePreference> TimePreferences
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TimePreference>("AMSModel.FK__TimePrefe__DayPr__412EB0B6", "TimePreferences");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TimePreference>("AMSModel.FK__TimePrefe__DayPr__412EB0B6", "TimePreferences", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="ErrorLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ErrorLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ErrorLog object.
        /// </summary>
        /// <param name="errorID">Initial value of the ErrorID property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="tableName">Initial value of the TableName property.</param>
        /// <param name="action">Initial value of the Action property.</param>
        public static ErrorLog CreateErrorLog(global::System.Int32 errorID, global::System.String message, global::System.String tableName, global::System.String action)
        {
            ErrorLog errorLog = new ErrorLog();
            errorLog.ErrorID = errorID;
            errorLog.Message = message;
            errorLog.TableName = tableName;
            errorLog.Action = action;
            return errorLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ErrorID
        {
            get
            {
                return _ErrorID;
            }
            set
            {
                if (_ErrorID != value)
                {
                    OnErrorIDChanging(value);
                    ReportPropertyChanging("ErrorID");
                    _ErrorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ErrorID");
                    OnErrorIDChanged();
                }
            }
        }
        private global::System.Int32 _ErrorID;
        partial void OnErrorIDChanging(global::System.Int32 value);
        partial void OnErrorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TableName
        {
            get
            {
                return _TableName;
            }
            set
            {
                OnTableNameChanging(value);
                ReportPropertyChanging("TableName");
                _TableName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TableName");
                OnTableNameChanged();
            }
        }
        private global::System.String _TableName;
        partial void OnTableNameChanging(global::System.String value);
        partial void OnTableNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="TimePreference")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TimePreference : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TimePreference object.
        /// </summary>
        /// <param name="timePrefID">Initial value of the TimePrefID property.</param>
        /// <param name="dayPrefID">Initial value of the DayPrefID property.</param>
        /// <param name="timeFrom">Initial value of the TimeFrom property.</param>
        /// <param name="timeTo">Initial value of the TimeTo property.</param>
        public static TimePreference CreateTimePreference(global::System.Int32 timePrefID, global::System.Int32 dayPrefID, global::System.TimeSpan timeFrom, global::System.TimeSpan timeTo)
        {
            TimePreference timePreference = new TimePreference();
            timePreference.TimePrefID = timePrefID;
            timePreference.DayPrefID = dayPrefID;
            timePreference.TimeFrom = timeFrom;
            timePreference.TimeTo = timeTo;
            return timePreference;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimePrefID
        {
            get
            {
                return _TimePrefID;
            }
            set
            {
                if (_TimePrefID != value)
                {
                    OnTimePrefIDChanging(value);
                    ReportPropertyChanging("TimePrefID");
                    _TimePrefID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TimePrefID");
                    OnTimePrefIDChanged();
                }
            }
        }
        private global::System.Int32 _TimePrefID;
        partial void OnTimePrefIDChanging(global::System.Int32 value);
        partial void OnTimePrefIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DayPrefID
        {
            get
            {
                return _DayPrefID;
            }
            set
            {
                OnDayPrefIDChanging(value);
                ReportPropertyChanging("DayPrefID");
                _DayPrefID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayPrefID");
                OnDayPrefIDChanged();
            }
        }
        private global::System.Int32 _DayPrefID;
        partial void OnDayPrefIDChanging(global::System.Int32 value);
        partial void OnDayPrefIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan TimeFrom
        {
            get
            {
                return _TimeFrom;
            }
            set
            {
                OnTimeFromChanging(value);
                ReportPropertyChanging("TimeFrom");
                _TimeFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeFrom");
                OnTimeFromChanged();
            }
        }
        private global::System.TimeSpan _TimeFrom;
        partial void OnTimeFromChanging(global::System.TimeSpan value);
        partial void OnTimeFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan TimeTo
        {
            get
            {
                return _TimeTo;
            }
            set
            {
                OnTimeToChanging(value);
                ReportPropertyChanging("TimeTo");
                _TimeTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeTo");
                OnTimeToChanged();
            }
        }
        private global::System.TimeSpan _TimeTo;
        partial void OnTimeToChanging(global::System.TimeSpan value);
        partial void OnTimeToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _Status;
        partial void OnStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__TimePrefe__DayPr__412EB0B6", "DayPreferences")]
        public DayPreference DayPreference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DayPreference>("AMSModel.FK__TimePrefe__DayPr__412EB0B6", "DayPreferences").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DayPreference>("AMSModel.FK__TimePrefe__DayPr__412EB0B6", "DayPreferences").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DayPreference> DayPreferenceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DayPreference>("AMSModel.FK__TimePrefe__DayPr__412EB0B6", "DayPreferences");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DayPreference>("AMSModel.FK__TimePrefe__DayPr__412EB0B6", "DayPreferences", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="membershipUserID">Initial value of the MembershipUserID property.</param>
        /// <param name="userFirstName">Initial value of the UserFirstName property.</param>
        /// <param name="userLastName">Initial value of the UserLastName property.</param>
        /// <param name="userTitle">Initial value of the UserTitle property.</param>
        /// <param name="companyID">Initial value of the CompanyID property.</param>
        public static User CreateUser(global::System.Int32 userID, global::System.Int32 membershipUserID, global::System.String userFirstName, global::System.String userLastName, global::System.String userTitle, global::System.Int32 companyID)
        {
            User user = new User();
            user.UserID = userID;
            user.MembershipUserID = membershipUserID;
            user.UserFirstName = userFirstName;
            user.UserLastName = userLastName;
            user.UserTitle = userTitle;
            user.CompanyID = companyID;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MembershipUserID
        {
            get
            {
                return _MembershipUserID;
            }
            set
            {
                OnMembershipUserIDChanging(value);
                ReportPropertyChanging("MembershipUserID");
                _MembershipUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MembershipUserID");
                OnMembershipUserIDChanged();
            }
        }
        private global::System.Int32 _MembershipUserID;
        partial void OnMembershipUserIDChanging(global::System.Int32 value);
        partial void OnMembershipUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserFirstName
        {
            get
            {
                return _UserFirstName;
            }
            set
            {
                OnUserFirstNameChanging(value);
                ReportPropertyChanging("UserFirstName");
                _UserFirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserFirstName");
                OnUserFirstNameChanged();
            }
        }
        private global::System.String _UserFirstName;
        partial void OnUserFirstNameChanging(global::System.String value);
        partial void OnUserFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserLastName
        {
            get
            {
                return _UserLastName;
            }
            set
            {
                OnUserLastNameChanging(value);
                ReportPropertyChanging("UserLastName");
                _UserLastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserLastName");
                OnUserLastNameChanged();
            }
        }
        private global::System.String _UserLastName;
        partial void OnUserLastNameChanging(global::System.String value);
        partial void OnUserLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserTitle
        {
            get
            {
                return _UserTitle;
            }
            set
            {
                OnUserTitleChanging(value);
                ReportPropertyChanging("UserTitle");
                _UserTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserTitle");
                OnUserTitleChanged();
            }
        }
        private global::System.String _UserTitle;
        partial void OnUserTitleChanging(global::System.String value);
        partial void OnUserTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserEmail
        {
            get
            {
                return _UserEmail;
            }
            set
            {
                OnUserEmailChanging(value);
                ReportPropertyChanging("UserEmail");
                _UserEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserEmail");
                OnUserEmailChanged();
            }
        }
        private global::System.String _UserEmail;
        partial void OnUserEmailChanging(global::System.String value);
        partial void OnUserEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserDescription
        {
            get
            {
                return _UserDescription;
            }
            set
            {
                OnUserDescriptionChanging(value);
                ReportPropertyChanging("UserDescription");
                _UserDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserDescription");
                OnUserDescriptionChanged();
            }
        }
        private global::System.String _UserDescription;
        partial void OnUserDescriptionChanging(global::System.String value);
        partial void OnUserDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserPhone
        {
            get
            {
                return _UserPhone;
            }
            set
            {
                OnUserPhoneChanging(value);
                ReportPropertyChanging("UserPhone");
                _UserPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserPhone");
                OnUserPhoneChanged();
            }
        }
        private global::System.String _UserPhone;
        partial void OnUserPhoneChanging(global::System.String value);
        partial void OnUserPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> UserStatus
        {
            get
            {
                return _UserStatus;
            }
            set
            {
                OnUserStatusChanging(value);
                ReportPropertyChanging("UserStatus");
                _UserStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserStatus");
                OnUserStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _UserStatus;
        partial void OnUserStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnUserStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CompanyID
        {
            get
            {
                return _CompanyID;
            }
            set
            {
                OnCompanyIDChanging(value);
                ReportPropertyChanging("CompanyID");
                _CompanyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyID");
                OnCompanyIDChanged();
            }
        }
        private global::System.Int32 _CompanyID;
        partial void OnCompanyIDChanging(global::System.Int32 value);
        partial void OnCompanyIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__Appointme__UserI__3F466844", "Appointments")]
        public EntityCollection<Appointment> Appointments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Appointment>("AMSModel.FK__Appointme__UserI__3F466844", "Appointments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Appointment>("AMSModel.FK__Appointme__UserI__3F466844", "Appointments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__Users__CompanyID__4316F928", "Company")]
        public Company Company
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("AMSModel.FK__Users__CompanyID__4316F928", "Company").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("AMSModel.FK__Users__CompanyID__4316F928", "Company").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Company> CompanyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("AMSModel.FK__Users__CompanyID__4316F928", "Company");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Company>("AMSModel.FK__Users__CompanyID__4316F928", "Company", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__UserPrefe__UserI__4222D4EF", "UserPreferences")]
        public EntityCollection<UserPreference> UserPreferences
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserPreference>("AMSModel.FK__UserPrefe__UserI__4222D4EF", "UserPreferences");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserPreference>("AMSModel.FK__UserPrefe__UserI__4222D4EF", "UserPreferences", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AMSModel", Name="UserPreference")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserPreference : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserPreference object.
        /// </summary>
        /// <param name="userPrefID">Initial value of the UserPrefID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="bookingDays">Initial value of the BookingDays property.</param>
        /// <param name="slotDuration">Initial value of the SlotDuration property.</param>
        public static UserPreference CreateUserPreference(global::System.Int32 userPrefID, global::System.Int32 userID, global::System.Int32 bookingDays, global::System.Int32 slotDuration)
        {
            UserPreference userPreference = new UserPreference();
            userPreference.UserPrefID = userPrefID;
            userPreference.UserID = userID;
            userPreference.BookingDays = bookingDays;
            userPreference.SlotDuration = slotDuration;
            return userPreference;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserPrefID
        {
            get
            {
                return _UserPrefID;
            }
            set
            {
                if (_UserPrefID != value)
                {
                    OnUserPrefIDChanging(value);
                    ReportPropertyChanging("UserPrefID");
                    _UserPrefID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserPrefID");
                    OnUserPrefIDChanged();
                }
            }
        }
        private global::System.Int32 _UserPrefID;
        partial void OnUserPrefIDChanging(global::System.Int32 value);
        partial void OnUserPrefIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookingDays
        {
            get
            {
                return _BookingDays;
            }
            set
            {
                OnBookingDaysChanging(value);
                ReportPropertyChanging("BookingDays");
                _BookingDays = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookingDays");
                OnBookingDaysChanged();
            }
        }
        private global::System.Int32 _BookingDays;
        partial void OnBookingDaysChanging(global::System.Int32 value);
        partial void OnBookingDaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SlotDuration
        {
            get
            {
                return _SlotDuration;
            }
            set
            {
                OnSlotDurationChanging(value);
                ReportPropertyChanging("SlotDuration");
                _SlotDuration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlotDuration");
                OnSlotDurationChanged();
            }
        }
        private global::System.Int32 _SlotDuration;
        partial void OnSlotDurationChanging(global::System.Int32 value);
        partial void OnSlotDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _Status;
        partial void OnStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__DayPrefer__UserP__403A8C7D", "DayPreferences")]
        public EntityCollection<DayPreference> DayPreferences
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DayPreference>("AMSModel.FK__DayPrefer__UserP__403A8C7D", "DayPreferences");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DayPreference>("AMSModel.FK__DayPrefer__UserP__403A8C7D", "DayPreferences", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AMSModel", "FK__UserPrefe__UserI__4222D4EF", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AMSModel.FK__UserPrefe__UserI__4222D4EF", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AMSModel.FK__UserPrefe__UserI__4222D4EF", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AMSModel.FK__UserPrefe__UserI__4222D4EF", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("AMSModel.FK__UserPrefe__UserI__4222D4EF", "Users", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
