//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace AMS
{
    public partial class AMSEntities : DbContext
    {
        public AMSEntities()
            : base("name=AMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActivityLog> ActivityLogs { get; set; }
        public DbSet<AppointmentAvail> AppointmentAvails { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DayPreference> DayPreferences { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
        public DbSet<TimePreference> TimePreferences { get; set; }
        public DbSet<UserPreference> UserPreferences { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
