//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AMS
{
    public partial class Customer
    {
        public Customer()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int CustomerID { get; set; }
        public int MembershipUserID { get; set; }
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public string CustEmail { get; set; }
        public string CustDescription { get; set; }
        public string CustPhone { get; set; }
        public Nullable<bool> CustStatus { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
    
}
