//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AMS
{
    public partial class DayPreference
    {
        public DayPreference()
        {
            this.AppointmentAvails = new HashSet<AppointmentAvail>();
            this.TimePreferences = new HashSet<TimePreference>();
        }
    
        public int DayPrefID { get; set; }
        public int UserPrefID { get; set; }
        public string Day { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<AppointmentAvail> AppointmentAvails { get; set; }
        public virtual UserPreference UserPreference { get; set; }
        public virtual ICollection<TimePreference> TimePreferences { get; set; }
    }
    
}
