//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AMS
{
    public partial class UserPreference
    {
        public UserPreference()
        {
            this.DayPreferences = new HashSet<DayPreference>();
        }
    
        public int UserPrefID { get; set; }
        public int UserID { get; set; }
        public int BookingDays { get; set; }
        public int SlotDuration { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<DayPreference> DayPreferences { get; set; }
        public virtual User User { get; set; }
    }
    
}
